### ISSUE TITLE
Clause de documentation

### ISSUE THREAD

**Issue by ValentinTrinque** [tibastral/contrats-francais#17]
Bonjour,

J'ai quelques interrogations quand à la non-présence d'une clause portant sur la documentation. Dans le manifesto des méthodes agiles, on peut y lire:

Je pense qu'il pourrait être intéressant d'ajouter cette clause explicitant la présence d'une documentation utilisateur et d'une documentation fonctionnelle à la livraison (sauf contre indication dans les CP).

Je comprend que le développement agile ne favorise pas cette étape de documentation mais il ne l'exclue pas pour autant.

Quand pensez-vous ?

PS: Merci pour ce dépôt vraiment chouette.

**Comment by tibastral** [comment]
Je pense qu’il faut laisser un maximum de liberté aux 2 parties.
Et les stories, si elles sont bien écrites, sont une excellente documentation !

- Thibaut

**Comment by ValentinTrinque** [comment]
Je comprend votre point de vue et suis-je d'accord avec le fait que les stories représentent en elles-mêmes une source de documentation.

Cependant, une clause explicitant cela ne serait-il pas plus "clair" vis-a-vis du contrat en lui-même ?

**Comment by tibastral** [comment]
peut-être, à voir :)

- Thibaut

**Comment by ValentinTrinque** [comment]
> peut-être, à voir :)

À voir comment ? ^^"

**Comment by tibastral** [comment]
Bah si vous tu as un avocat prêt à expliquer ça mieux (law court complient), go :)

**Comment by ValentinTrinque** [comment]
Je vois, merci.
