### ISSUE TITLE
Evoquer les Histoires Utilisateur

### ISSUE THREAD

**Issue by ValentinTrinque** [tibastral/contrats-francais#18]
Bonjour,

Je pense qu'il serait important de citer, dans les méthodes de travail, la mise en place de User Stories pour définir les spécifications fonctionnelles définies par le Client, sous la forme de cas simples et factuels. Ce qui constituerai en soit l'Icebox. Cela permettrai d'être clair sur les fonctionnalités à développer et, en même temps, définir ce qui est de l'ordre de l'*Évolution* ou pas.

Qu'en pensez-vous ?

**Comment by tibastral** [comment]
C’est une très bonne idée. Décrire un peu mieux ce qu’est une user story, je le fais dans le document stories.md, mais il est vrai que ce n’est pas intégré au contrat. Si tu as une idée, je suis partant. Par contre, il faut que ce soit validé par un avocat.

- Thibaut

**Comment by ValentinTrinque** [comment]
D'accord. Je vais voir ce que je peux faire.

**Comment by tibastral** [comment]
Je ferme en attendant tes retours
