### ISSUE TITLE
Licences "Open-source" ou "libres"

### ISSUE THREAD

**Issue by ValentinTrinque** [tibastral/contrats-francais#19]
En effectuant des recherches, je suis tombé sur un contrat "type" des méthodes agiles.

[Contrat de prestation de services réalisés selon les méthodologies agiles - http://www.contrat-agile.org/](http://www.contrat-agile.org/contrats/Contrat_Agile_V1.1.pdf)

Il y est évoqué un point très important: les licences open-source est libre.

Je cite la page 15:

>Le CLIENT est informé que les Développements et le Logiciel sont susceptibles d’intégrer des modules ou des bibliothèques dites « libres » ou « open source » dont les licences peuvent contenir des exclusions pures et simples de toutes garanties.
>
>Dans ce cas, le CLIENT accepte que LE PRESTATAIRE ne puisse lui conférer plus de garantie qu’elle n’en tient elle-même des licences de ces modules ou bibliothèques. LE PRESTATAIRE exclut par conséquent toute garantie relative aux modules ou bibliothèques dites « libres » ou « open source » dont les licences contiendraient une exclusion de garantie.
>
>Le CLIENT pourra prendre connaissance de l’étendue des garanties associées aux modules ou bibliothèques dites « libres » ou « open source » en se reportant aux licences de celles-ci que LE PRESTATAIRE joindra systématiquement au code, lorsque ces licences l’imposent, lors de la livraison des Développements ou du Logiciel concernés.

Je pense que cette clause pourrait être très intéressante pour ce contrat.

Qu'en pensez-vous ?

**Comment by tibastral** [comment]
C’est très intéressant, et je pense qu’il faudrait clairement ajouter ça aux CGV ! Excellent !

- Thibaut

**Comment by ValentinTrinque** [comment]
Voulez-vous que je fasse Pull Request avec ce contenu ou voulez-vous une validation d'avocat ?

**Comment by tibastral** [comment]
Pourquoi pas une pull request, et le mieux serait de faire valider ça par un avocat, oui !

- Thibaut

**Comment by tibastral** [comment]
En attente :)
