### ISSUE TITLE
An error occurred while installing libv8 (3.16.14.7)

### ISSUE THREAD

**Issue by EhabElia** [tibastral/contrats-francais#20]
Hello Thibault,
D'abord merci pour ton travail et de l'avoir partager en OS.
J'ai rencontré le problème en titre et ai essayé tout ce que google m'a sorti sans succès. Peut-être c'est à cause d'El Capitain ?

**Comment by EhabElia** [comment]
Je l'ai trouvé et c'est bien à cause d'El Capitain.
Il suffit de faire 
    `$ bundle update libv8`
en japonnais mais utile http://qiita.com/ganta/items/53f616b48e94d989952f

**Comment by tibastral** [comment]
C'est bon c'est fixé dans la nouvelle version. Merci pour ce retour
