### ISSUE TITLE
Inversion de termes dans "cga"

### ISSUE THREAD

**Issue by PJoy** [tibastral/contrats-francais#24]
> Lorsque le Sous-traitant estime que le Livrable est achevé, le Sous-traitant adresse à NomSociété le Livrable dans sa version définitive. NomSociété peut alors émettre des réserves dans un délai de 1 mois. A défaut de réserve dans le délai précité, la version définitive du Livrable est considérée comme tacitement réceptionnée par le NomSociété.

Il me semble ici que "le Sous-traitant" et "NomSociété" sont inversés. En effet "NomSociété" constitue la société du freelance, ce n'est pas lui qui réceptionne le "Livrable".

**Comment by tibastral** [comment]
C'est très cool ! N'hésitez pas à corriger, je mergerai avec grand plaisir !
