### ISSUE TITLE
Cession des droits d'auteur et Iceblock

### ISSUE THREAD

**Issue by AxelBriche** [tibastral/contrats-francais#25]
Bonjour et merci pour le partage de ces documents.

J'aimerais savoir ce qu'est un "Icebox", c'est bien le document dans lequel le client expose tout ses besoins pour son projet ? (ex : fonctionnalités et pages à mettre en place).

J'aimerais aussi savoir si dans le cas ou l'on souhaite céder les droits d'auteur, si ce document est ok tant que l'on mentionne la cession des droits d'auteur au client dans les Condition Particulières svp.

Enfin, savez vous où il est possible de trouver un document similaire mais davantage adapté à un travail au forfait svp ?

Merci.

**Comment by tibastral** [comment]
1 -
Oui

2-
Je pense => à valider avec un avocat

3-
Certainement que ça existe, mais comme je n'en fais jamais (je déteste les forfaits), je n'en ai pas.

**Comment by AxelBriche** [comment]
Merci pour la réponse rapide :)
