### ISSUE TITLE
Facturation des Itérations

### ISSUE THREAD

**Issue by yachaka** [tibastral/contrats-francais#28]
Salut !

Tout d'abord merci pour ce dépot, c'est génial :)

J'avais une question concernant la facturation des Itérations :

Dans les C.G.V., il est écrit que le paiement interviendra avant le commencement de chaque itération.  
Puis dans les C.P., il est écrit le montant exact des prestations.

Imaginons que je vais faire 150 heures avec un client, donc :
- J'écris 150 heures de prestation et le montant total dans les C.P.
et
- Je fais un Devis pour les 150 heures ? (VS un Devis par itération)
puis
- Je fais une facture par Itération ? avec la date d'échéance au démarrage de l'itération

Si tu peux m'aider sur ces questions, c'est super !
Merci !

**Comment by tibastral** [comment]
Fais toujours valider les choses par un avocat.

Après, moi, le contrat me sert de framework global, ensuite, dans les faits je signe une fois le contrat et ensuite, je facture avec une facture classique
